[package]
org = "tharmigank"
name = "http.client.wrapper"
version = "@toml.version@"
authors = ["tharmigank"]
keywords = ["http", "client", "wrapper", "interceptor"]
repository = "https://github.com/TharmiganK/module-tharmigank-http-client-wrapper"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.tharmigank.http"
artifactId = "http-client-wrapper-native"
version = "@toml.version@"
path = "../native/build/libs/http.client.wrapper-native-@project.version@.jar"
